services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    container_name: kafka-service # if you have a dependency on kafka, now inside your docker container, your broker will be "kafka-service:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  fastapi_webapp:
    build:
      context: .
      dockerfile:  ./python-app/Dockerfile # Build the Dockerfile from the python-app directory
    container_name: fastapi-app
    volumes:
      - ./python-app:/app  # Mount the app directory for live updates
      - ./client_secret.json:/app/client_secret.json  # Mount the secret.json file
    environment:
      - SECRET_FILE=/app/client_secret.json
      - KAFKA_BOOTSTRAP_SERVERS=kafka-service:9092
    ports:
      - "8000:8000"
    depends_on:
      - kafka